google_analytics_id: 
piwik_analytics_site_id: 

repository: https://github.com/

timezone: Asia/Shanghai

name: 奇货导航 · QIHUO-Navi
author: 奇货队长
author_url: http://qidui.me
organization: TEELAB
organization_url: http://teelab.net
description: A Navigation Website for QIHUO
keywords: 奇货导航, QIHUO-Navi, QIHUO, Navi, Navigation
url: http://fav.qihuo.me
contact: dongxibitan[at]gmail[dot]com

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
